Resources:
  UserinfoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Userinfo
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: Production
